### ISSUE TITLE
Getting Error in test.py

### ISSUE THREAD

**Issue by NishaatK** [rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning#7]
Hi @rohitnaik246 ,
I'm referring your project. I've created random_forest.pkl using train.py but getting error in test.py:
ValueError: Number of features of the model must match the input. Model n_features is 30 and input n_features is 22 
![error](https://user-images.githubusercontent.com/49118036/55288005-8d452c80-53ce-11e9-91b6-7253e30d3ac7.jpg)
I'm using Python 2.7 and Windows 7(32 bit). How to resolve it?

**Comment by rohitnaik246** [comment]
The error is because the test set obtained from features_extraction.py has 22 features, whereas the model you created has 30 features. For better understanding why this has happened, can you please provide me some information about -
1. You said you have created random_forest.pkl using train.py. What all modifications have you made to train.py?
2. Any other changes you have made in the package?

**Comment by NishaatK** [comment]
Thank you for your response. The error is resolved.

**Comment by rohitnaik246** [comment]
Great. Glad I could help!
